### ISSUE TITLE
Welcome to Chiltern-Route-v2 Discussions!

### ISSUE THREAD

**Issue by DocMartin7644** [DocMartin7644/Chiltern-Route-v2#2]
### Discussed in https://github.com/DocMartin7644/Chiltern-Route-v2/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **DocMartin7644** July 25, 2022</sup>
I go by the handle DocMartin.  I have recently started using GitHub to develop a route for a train simulation program called Open Rails.  The repository for my route is DocMartin7644/Chiltern-Route-v2.  I have recently made the repository public in order to share my work with other train simulation enthusiasts.  Since my route is a work-in-progress and is continually being updated with new additiions, GitHub and GitHub Desktop work very effectively for its distribution and updating.

Obviously I like to keep track of how many users have cloned or downloaded the route but I find the statistics in Insight > Traffic rather difficult to interpret and wonder whether someone can help me with this.

This is a screenshot of the relevant traffic details:

![GitHubStats](https://user-images.githubusercontent.com/98037803/180863248-a5d59b1c-9498-4143-b821-dd428cf60213.jpg)

Question 1: why the difference between the figures highlighted in red?  Do they mean that some people have cloned the route more than once?
Question2:  Why do the two sets of figures highlighted in yellow not correspond?  The total in the "Referring sites" box does not correspond to the numbers in the graph immediately above it.  Why not?  The same applies to the figures highlighted in green.
Questiion 3:  Users have the option to download a zip file of the project rather than cloning it.  However, I can find no statistics of the number of such downloads.  Am I missing something or is it the case that no statistics of zip downloads are recorded.

I would be very interested and grateful to receive any replies to this post.

DocMartin</div>

**Comment by DocMartin7644** [comment]
Hi Mike,

I'm not quite sure what the point is that you are making unless it be to
prove that GitHub is working properly!  Keep an eye on GitHub as I will
soon be committing to it the latest additions to the scenery.

All the best,

Martin

**Comment by Papyrus2750** [comment]
Hello Martin,

I've been working on your downloaded route and had a question regarding implementing Paddington Station. I've managed to create a model of the station in Blender and have successfully installed the .s exporter. However, upon placing it in the TSRE5 editor, I encounter an issue where a transparent bounding cube appears.

Oddly, I experimented with a smaller object like a cube, and it worked okay. Could you kindly offer some guidance or advice on the best approach to integrate the station model into the editor?

Thank you for your time and assistance.

Best regards,
Papyrus

**Comment by Papyrus2750** [comment]
Hi Martin,

I hope you're doing well. I'm writing to gently remind you about the
Blender models I shared for Paddington Station. I understand things can get
busy, and it's possible that the email might have slipped your attention.

Whenever you get a chance, could you confirm if you've had the opportunity
to access the files?

Thank you for your time.

Best regards,
Papyrus

**Comment by DocMartin7644** [comment]
Hi Papyrus,

I would certainly have had a look at the files if I had known where they are!  Did you send them to my email?  If so, they never got through.  Can you send them again and I will definitely take a look?

Martin

**Comment by DocMartin7644** [comment]
Papyrus,  I take it that you did mark the files as shared?

Martin

**Comment by Papyrus2750** [comment]
I think this time I've done it well. You should receive them in the 'Shared
with me' folder in Google Drive.

**Comment by Papyrus2750** [comment]
Thank you for suggesting OneDrive for sharing the files. Could you please
provide me with your Microsoft email address? This will allow me to send
the invitation to the correct account.

**Comment by DocMartin7644** [comment]
My email is docmartin7644@gmail.com

**Comment by Papyrus2750** [comment]
I've generated the link for the file:  paddinghton(white).zip
<https://1drv.ms/u/s!AiaeF2bURAZIbEneFbx15J7eKao?e=oeDPtA>   I don't think
it's necessary, but I wanted to provide it just in case.

**Comment by DocMartin7644** [comment]
Thanks, Papyrus.  I now have successfully downloaded the file.  However, after all this I don't know how much help I can be to you.  I was expecting to receive MSTS/OR .s and .sd files which I could place in my route and take a look at in situ.  But you have sent a .blend file, which I take it is the modelling file that you have created in Blender.  Now, unfortunately, I have never used Blender (though I am willing to learn!).  I do have Blender 2.79 on my computer but when I load in your file all I can see is a tiny rectangle.  Also I have downloaded but not yet installed the Blender to MSTS exporter.  So, where do we go from here?

Martin

**Comment by Papyrus2750** [comment]
I've sent you a .s file of the model, but I haven't created a .sd file as I
haven't felt it necessary. To clarify, I used another shape's file, renamed
it to represent the Paddington model. As far as I understand, .sd files are
primarily for noise, and their absence shouldn't affect the model. As for
the rectangle, I'm not sure what's happenning. Anyway, could you please
share what software you use for modeling if it's not Blender?
padd.s <https://1drv.ms/u/s!AiaeF2bURAZIcGpcSDiV0cJdpNk?e=Y7GjCp>

Papyrus

**Comment by DocMartin7644** [comment]
OK, I tried installing the .s file in my copy of the route and all I got was a blue wireframe of a rectangular box.  When I tried looking at the model in ShapeViewer I got an error message.  So I am guessing that somehow the export from Blender to MSTS format has not worked properly.

It is my understanding that for models such as buildings the .sd file is needed so that you can specify alternative texture files for snow textures and night textures.  For items of rolling stock the .sd file is needed to specify the bounding box.

I am still using Train Sim Modeler to make my models.  I have sometimes felt the need for a more powerful program such as 3DCrafter or Blender but I have so far been put off by the steep learning curve!

Martin

**Comment by Papyrus2750** [comment]
Thank you for the clarification, Martin. I wasn't aware of the crucial role
.sd files play in specifying textures and bounding boxes. I apologize for
the inconvenience caused. I'll work on resolving the issue with the export
from Blender to MSTS format.

**Comment by DocMartin7644** [comment]
No need to apologize, Papyrus.  There is always something new to learn!  Good luck with sorting out the model.

**Comment by Papyrus2750** [comment]
This one does appear in my Shape Viewer. Hopefully, it will appear in yours
as well.
paddw <https://1drv.ms/f/s!AiaeF2bURAZIdKn8oiX1f-Jm3-8?e=qDUl8e>

**Comment by DocMartin7644** [comment]
Brilliant, Papyrus!  Not only does your model appear in Shape Viewer, it also, once I added the details in the ref file, appears in the route.  I have managed to place it, somewhat roughly, in my copy of the route.  What would be very helpful, assuming you have it accurately positioned in your copy of the route, would be your x, y, z position coordinates so that I too can have it located precisely.

One small point.  I assume that you realize that the file you have named paaddnou.sms.txt needs to be renamed to paaddnou.sd

Now all we need is some textures!

Thank you so much for sharing.  Let me know if there is anything I can do to help with the texturing.

Martin

**Comment by Papyrus2750** [comment]
Thank you for the information, Martin. To obtain the precise coordinates, I
need to enter the model into the route, but I'm unsure about what to write
in the reference file. For instance, I've used the following:

Static (
Class ( "SIGNAL BOXES" )
Filename ( paaddnou.s )
Align ( None )
Description ( Paaddnou )
)

Could you confirm if this format is correct or if there's a different
structure required for integrating the model accurately into the route's
reference file?

**Comment by DocMartin7644** [comment]
Yes, you have the format correct.  My only suggestion is that you call the class "STATIONS" rather than "SIGNAL BOXES"

Martin

**Comment by DocMartin7644** [comment]
Hi Papyrus,

By the way, having placed your model in the route, I do not see evidence of the transparent bounding cube problem which started off this discussion.  Maybe I am not looking in the right place or you have managed to solve the problem.

Martin

**Comment by Papyrus2750** [comment]
Hi Martin,

I'm encountering difficulty placing any, not just my, object from the
reference file into TSRE. It's possible the trackwork might require editing
if you intend to incorporate my model into your route, as I haven't
utilized it for guidance. Regarding textures, I'm still learning the basics
and am unsure how to implement them properly.

You're correct about the transparent cube issue. I suspect it might be due
to an error on the .sd file. I wasn't aware of the necessity to rename the
paddnou.sms.txt, so thank you for pointing that out.

Wishing you happy holidays,
Papyrus

**Comment by DocMartin7644** [comment]
Hi Papyrus,

Oh, I had assumed that you had used my trackwork to guide your building of the model.  It looks to me as though the model does not quite fit the track exactly.  Some of the platforms overlap the track.  I am afraid it is simply not feasible for me to alter the track to fit the model.  This would involve too many changes and have a knock-on effect on other sections of track.  Although not entirely simple, it would be much better to adjust the model to fit the trackwork.  What you really need is to take an overhead screenshot of the trackwork and use this as a backdrop to guide the building of the model.  Maybe I am wrong but it is my understanding, however, that using backdrops is not as easy in Blender as it is in, for example, Train Sim Modeler.  If it is not possible to adjust the model, I will have to try building my own model of the station.  

What is the difficulty you are meeting in placing objects in TSRE?  It is quite a straightforward process, so let me know if I can offer any advice.

I hope you can master the art of texturing.  I believe in the dictum "Good textures can save a bad model but bad texures can ruin a good one".  So good luck with that!

Merry Christmas to you too.

Martin

**Comment by Papyrus2750** [comment]
Hi Martin

Of course, I should have considered the trackwork. I apologize for not
recognizing that earlier; it seems rather obvious now. I'll rectify the
issue by removing the platforms and aligning them according to the
station's layout. I've gained some knowledge about textures and feel
confident in implementing them accurately.

Best regards
Papyrus

**Comment by DocMartin7644** [comment]
Hi Papyrus,

As I said before, the best way to modify the platforms so that they fit the trackwork is to take a vertical screenshot of the tracks in TSRE.  Try to get the camera as exactly over the tracks as you can.  You may have to do this in stages rather than try to take the whole station in a single screeshot.  Then use the screenshot(s) as a background picture in Blender to guide your modelling.  I do not know how you implement backgrounds like this in Blender but doubtless you will be able to find out how to do it.  Even so, in the end you will probably have to fine tune the model once you have placed it in the route.

I am glad to hear that you are confident you can make the necessary textures.  Please do keep me informed of your progress and let me know if I can help in any way.

All the best,

Martin

**Comment by Papyrus2750** [comment]
Hi Martin
I've made progress on remodeling the station, but I encounter an 'Error 5 -
Invalid procedure call or Argument' every time I try to open it in the
Saper viewer. Could you provide insights into what this error signifies?

Papyrus

**Comment by DocMartin7644** [comment]
Hi Papyrus,
Glad to hear you are making progress.  I have come across this error several times.  Unfortunately, I do not know its significance.  There is a program called Shape Fix.  If you can locate it, you might try running the model through that but I don't know whether it will help.  My only real suggestion is that you could post on Elvas Tower to see if anyone has any thoughts on the problem.

Martin

**Comment by Papyrus2750** [comment]
Thank you for the suggestions. I appreciate your advice on using Shape Fix.
However, I've encountered difficulty finding a working download link for
it. Could you share where you obtained Shape Fix, and did it prove
effective for the errors you encountered? I'd like to explore this option
before reaching out on Elvas Tower.

**Comment by DocMartin7644** [comment]
[Shape Fix.zip](https://github.com/DocMartin7644/Chiltern-Route-v3/files/14015663/Shape.Fix.zip)

I expect I got the Shape Fix program from the now defunct UKTrainSim site.  I am attaching my copy and hope it reaches you safely.  That said, I honestly don't know whether it will solve your problem but it's worth a try.

Martin

**Comment by Papyrus2750** [comment]
Hi Martin,

Unfortunately, Shape Fix didn't work, so I've decided to try out TSM and
see if it works better. However, when I try to export it, I get the
following error message:

"Error converting texture file! C:\Program Files\Microsoft games\Train
Simulator\utils\makeace"blank bmp""blank.ace"-dxt"

Although it creates the .s and .sd files, when I open the .s file in Shape
Viewer, I receive the error message "Error - S file not unicode".

How can I fix this?

Thanks, Atserias

**Comment by DocMartin7644** [comment]
I have had the failure to convert texture file message quite often.  So now I always use the AceIt program to convert the textures independently of TSM.

I am not sure what the reason for the s file not unicode error is.  Again, if you can send me the TSM project files, I will investigate.

Martin

P.S  Are you Papyrus, Atserias or somebody else?!

**Comment by Papyrus2750** [comment]
Here is the folder containing the object I've created to test TSM. It's a
simple cylinder with a red face; the other faces are textured in white.
shape <https://1drv.ms/f/s!AiaeF2bURAZIgQevtn8E97W6J2Wy?e=0SdDx8>

**Comment by Papyrus2750** [comment]
P.S. Yes, I am Atserias, but for internet purposes, I go by the nickname
Papyrus. Apologies for any confusion.

**Comment by DocMartin7644** [comment]
Thanks for sending the cylinder project files.  I had no difficulty in converting the textures and making good .s and .sd files, which all opened in Shape Viewer without problem.  So, not being able to reproduce your problem, I am afraid I do not know what to suggest.  If I do have any bright ideas, I will let you know.

Thanks also for clarifying about your names.  Now I am curious about your nationality!

Martin

**Comment by Papyrus2750** [comment]
Thank you for reviewing the project files. I'm glad to hear that the
textures converted smoothly and the .s and .sd files opened without any
issues in Shape Viewer.

Regarding the problem I encountered, I suspect it might be related to the
TSM folder or the MSTS Utils folder. I've attached some screenshots for
reference. It appears that the "ffedit" folder is empty, which leads me to
believe that I may be missing the "ffedit_unicode.exe" file. I attempted to
use the "FFEDIT_sub.exe" file from TSSH as a replacement, but
unfortunately, it didn't resolve the issue.

On another note, I'm from Barcelona, Catalonia.

Best regards,

Atserias

**Comment by Papyrus2750** [comment]
File Explorer 2_16_2024 3_34_46 PM.png
<https://1drv.ms/i/s!AiaeF2bURAZIgRdGfwgE7ZyEo5RJ?e=LrCb7B>
File Explorer 2_16_2024 3_37_56 PM.png
<https://1drv.ms/i/s!AiaeF2bURAZIgRix3XCsGSCZHVTx?e=6fEPOc>

**Comment by DocMartin7644** [comment]
See whether the attached copy of ffedit works for you.  I hope you can download the attachment OK.
[ffedit_sub_v1-2.zip](https://github.com/DocMartin7644/Chiltern-Route-v3/files/14313197/ffedit_sub_v1-2.zip)

I used to know Barcelona quite well many years ago having visited it many times.  I have bought lots of books at the bookstalls in Las Ramblas!  Do they still exist?  Is your mother tongue Catalan or Spanish?
I am British but live in Louisiana, USA.

Martin

**Comment by Papyrus2750** [comment]
I'm afraid it's the same version I have. Is there anything missing in any
of the other folders? Also, should the ffedit folder contain only the
ffedit_unicode.exe, or should there be additional files?

Yes, there are still bookstalls, especially for Sant Jordi, a holiday
celebrated on April 23rd. We do mostly speak Catalan even though there's
always someone who won't bother learning it. I've never been to Louisiana
but I've been to California and Massachussets.

**Comment by DocMartin7644** [comment]
This is what my FFEdit folder contains:

![FFEdit](https://github.com/DocMartin7644/Chiltern-Route-v3/assets/98037803/82bac73d-5ed9-46da-bbd9-ab15e68fdbbc)

I know Spanish but I know only one word of Catalan - tangut - because I have seen it on the sign hanging in shop doors!

**Comment by Papyrus2750** [comment]
I don't see what's different. I'll just make the model in TSM and then send
it so you can export it. But can you please send me the exported model of
the test cylinder? Not just the .s and .sd files, but also the textures and
BMP and TSM files. Thanks

Regarding "tangut," I'm not sure what it means. Could it have been
"tancat," which means closed?

**Comment by DocMartin7644** [comment]
Is this what you wanted?
[4Papyrus.zip](https://github.com/DocMartin7644/Chiltern-Route-v3/files/14351087/4Papyrus.zip)

This shows you how bad my memory is!  Of course, I meant "tancat"!
